///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
METER ---------------------------------------------------------------------------------------------------------------------------------

[Icon]
Meter=IMAGE
MeterStyle=sIcon
X=#Margin#

[Text]
Meter=STRING
MeterStyle=sString
StringAlign=LeftCenter
X=R
W=80

[spacer]
Meter=IMAGE
SolidColor=0,0,0,1
X=R
Y=R
W=#Margin#
H=#Margin#