///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
METER ---------------------------------------------------------------------------------------------------------------------------------

[Text]
Meter=STRING
MeterStyle=sString
StringAlign=RightCenter
AntiAlias=1
X=80

[Icon]
Meter=IMAGE
MeterStyle=sIcon
X=80+#Margin#

[spacer]
Meter=IMAGE
SolidColor=0,0,0,1
X=R
Y=R
W=#Margin#
H=#Margin#